# Generated by Django 4.2.5 on 2023-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0002_userprofile_realmprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=255)),
            ],
        ),
    ]
